<a href="https://colab.research.google.com/github/kangaroocather/sd2/blob/main/lab_session_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science - CMP020N205
## Lab Session 2 -  Probabilitiy and Linear Algebra for Data Science

###  1. Importing Library: Numpy
(From week 1 Lab, you can find more information about **"NumPy"** library).

NumPy is the fundamental Python library for numerical computing.

In [ ]:
import numpy as np

### 2. Importing Library: SciPy
(From Last week's Lab, you can find more information about **"SciPy"** library).

**SciPy** stands for Scientific python. For some statistical calculation we do need Scipy e.g, during last week, you have used stats from Scipy to calculate "Mode".



In [ ]:
from scipy import stats

### 3. Importing Library: Math

**Math** is a library you can apply for performing mathematical tasks by using different Math methods in this library.

In [ ]:
import math as mt

### 4. Importing Library: Random
Python has a built-in library **random** which can be used for generating random numbers/values


In [ ]:
import random as rnd

### 5. Matrix Operations
There are different ways that we can represent Matrix in Python. We will see how we can represent Matrix using NumPy Library.

An example code is provided below:

In [ ]:
x = np.array( ((2,3), (3, 5)) )
y = np.array( ((1,2), (5, -1)) )
addition= x+y
print ("addition of x and y", addition )

subtraction = x-y
print ("difference between x and y", subtraction )

dot_product= np.dot(x,y)
print ("dot product of x and y", dot_product )



addition of x and y [[3 5]
 [8 4]]
difference between x and y [[ 1  1]
 [-2  6]]
dot product of x and y [[17  1]
 [28  1]]


There is another function in **NumPy** called **matrix()** that provide convinient notations of Matrix multiplication. Using the **matrix()** function when we will do x*y it actually gives us the "dot product multiplication" whereas, for NumPy array only does "element-wise" multiplication.

Therefore, to find the multiplication in our previous example we used np.dot function for getting the multiplication while using numpy array.

**Another important note,** Numpy matrix() is strictly two dimensional, while NumPy array can be of any dimension.

We have an example below, where we used NumPy Matrix to perform a matrix multiplication

In [ ]:
x = np.matrix( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)) )
multiplication = x * y
print ("multiplication of x and y", multiplication )


multiplication of x and y [[17  1]
 [28  1]]


## Question 1
You are given with metrices "a" contains ((45,35), (21,51)) , "b" contains ((1,2), (3,4)) and, "c" contains ((100,101), (200,201)). Now perform the following operations given:

***Hint:*** You can either use "array" or "matrix" function.



1.   a+b
2.   b-c
3. a*c
4. b.c

In [ ]:
import numpy as np


a = np.matrix(((45,35), (21,51)))
b = np.matrix( ((1,2), (3,4)))
c = np.matrix( ((100,101), (200,201)))

addition = a + b
print("addition of a and c:\n", addition)

subtraction = b-c
print("subtraction of a and c:\n", subtraction)


multiplication = a * c  # Equivalent to np.matmul(a, c) or a.dot(c)
print("Multiplication of a and c:\n", multiplication)



addition of a and c:
 [[46 37]
 [24 55]]
subtraction of a and c:
 [[11500 11580]
 [12300 12372]]
Multiplication of a and c:
 [[11500 11580]
 [12300 12372]]


In [ ]:
import numpy as

### 6. Vector Operations
There are different ways that we can represent Vector in Python as well. We will see how we can represent Vector using NumPy Library.

An example code is provided below:

In [ ]:
x = np.array( [1, 2, 5] )
y = np.array( [5,-1, 6])
addition= x+y
print ("addition of x and y", addition )

subtraction = x-y
print ("difference between x and y", subtraction )

multiplication = x*y
print ("multiplication between x and y", multiplication)

dot_product= np.dot(x,y)
print ("dot product of x and y", dot_product)



addition of x and y [ 6  1 11]
difference between x and y [-4  3 -1]
multiplication between x and y [ 5 -2 30]
dot product of x and y 33


There is no such function available for calculating Vector Modulus in NumPy or, in any other commonly used Python libraries.

Therefore, there are several work arounds and here one of them is given below:

In [ ]:
x=np.array([1,2,3,4,5])

modulus=np.sqrt(np.dot(x,x)) #np.dot(v,v) multiplies the elements of v with themselves and squares them before adding
print(modulus)


7.416198487095663


We will now see an example of multiplication of vector with a scalar value. We can simply use multiply() function in this occassion.

In [ ]:
import numpy as np
vector = np.array([1, 2, 3])
n = 100
np.multiply(vector,n)

array([100, 200, 300])

## Question 2
You are given with a vector/1D matrix, ([90,200,20,1,54,200]) contains the club card points he earned on different occassions. You are giving him 2 times more points and you want to store that 2 times rewarded points in a new vector/1D array. Write a code to store this infomation.


In [ ]:
import numpy as np
original_points=np.array([90,200,20,1,54,200])
double_points=original_points*2
print("Original Points:", original_points)
print("Doubled Points:", double_points)

Original Points: [ 90 200  20   1  54 200]
Doubled Points: [180 400  40   2 108 400]


### 7. Generating Binomial Distribution
We will now see how we can generate a Binomial Distribution and we will find the PMF, CMF and other statistical measures using **Stats** function from **SciPy** library.

Following is an example code given, for function binom(n=10,p=0.2), where, n is the number of trials and p holds the probability of success.

In [ ]:
from scipy import stats
X = stats.binom(10, 0.2)  # Declare X to be a binomial random variable
print(X.pmf(3))           # P(X = 3) which implies we are calculating the mass function for the third trial
print(X.cdf(4))           # P(X <= 4) which implies we are calculating cumulative distribution upto fourth trial
print(X.mean())           # Mean
print(X.var())            # Variance
print(X.std())            # Standard Deviation

0.20132659199999992
0.9672065024
2.0
1.6
1.2649110640673518


## Question 3
You are given a dice which you can roll five times to check how many times you find "6" and probability of the roll being a success is 80%.  Write a code to find the probability mass function cumulative distribution function for the final trial.

In [ ]:
from scipy import stats
X = stats.binom(5, 0.8)  # Declare X to be a binomial random variable
print(X.pmf(5))           # P(X = 3) which implies we are calculating the mass function for the third trial
print(X.cdf(5))


0.3276800000000001
1.0


### 8. Generating Normal Distribution
We will now see how we can generate a Normal Distribution and we will find the PDF, CDF and other statistical measures using Stats function from SciPy library. Here, we will also use Math library for some mathematical calculation.

Following is an example code given, for function norm($μ=3,σ^2=16$), where, μ is the mean and $σ^2$ is the Variance. In theory we can use Variance for calculation, however, in **SciPy we need to use Standard Deviation**. Hence, we will calculate square root of Variance.

In [ ]:
import math
from scipy import stats
A = stats.norm(3, math.sqrt(16)) # Declare A to be a normal random variable with mean equals 3 and variance equals 16
print(A.pdf(4))       			 # f(4), the probability density at 4
print(A.cdf(2))                  # f(2), cumulative probability at 2

0.09666702920071232
0.4012936743170763


## Question 4
Write a code to calculate the probability density function and cumulative distrbution function for a normal distribution with $μ=9 ,σ^2=64$, for probability density 6


In [ ]:
import math
from scipy import stats
A = stats.norm(9, math.sqrt(64))
print(A.pdf(6))       			 # f(4), the probability density at 4
print(A.cdf(2))



0.04648188673372112
0.19078695285251068


## Question 5
Write a code to calculate the normal probability density function for value "11" in the range, given, mean=10 and standard deviation=2.
**Hint:** remember to use standard deviation instead of variance in the code.

### 9. Calculating Probability and Conditional Probability

Here, we will see examples of probability calculation from a random variable. To do so, we will use **random** library from python.

From a tossing coin we have two events in a sample space.

The following code calculates the probability of getting head when we do  **ten, hundred, and thousand** trials of flip for an **fair** coin which **50% or below** will be the probability of getting heads from random flips


In [ ]:
def toss_coin(n):
    trials = []
    for i in range(n):
        trials.append(rnd.random() <= 0.5) #we are considering 50% or below will be the probability of getting heads from random flips
    return sum(trials) #returns the event count for observed heads from coin flips

def probability(n, e):
  probability_heads=(e/n)
  return probability_heads


n=10
probability_heads =probability(n, toss_coin(n))
print(probability_heads)

n=100
probability_heads =probability(n, toss_coin(n))
print(probability_heads)

n=1000
probability_heads =probability(n, toss_coin(n))
print(probability_heads)

0.5
0.52
0.491


##  Question 6
Now, calculate the probability of finding  "Tails" when you toss a **fair coin** with 50% or more will be the probability of getting tail from random fair flips.

Write a code to calculate the probability of getting head when we do  **ten, hundred, and thousand** trials of flip

In [ ]:
def toss_coin_tails(n):
    trials = []
    for i in range(n):
        trials.append(rnd.random() >= 0.5)
    return sum(trials)

def toss_coin_heads(n):
    trials = []
    for i in range(n):
        trials.append(rnd.random() < 0.5)
    return sum(trials)

def probability(n, e):
    return e / n


n_values = [10, 100, 1000]
for n in n_values:
    probability_tails = probability(n, toss_coin_tails(n))
    print(f"Probability of getting Tails in {n} trials: {probability_tails}")


for n in n_values:
    probability_heads = probability(n, toss_coin_heads(n))
    print(f"Probability of getting Heads in {n} trials: {probability_heads}")


Probability of getting Tails in 10 trials: 0.6
Probability of getting Tails in 100 trials: 0.55
Probability of getting Tails in 1000 trials: 0.494
Probability of getting Heads in 10 trials: 0.7
Probability of getting Heads in 100 trials: 0.44
Probability of getting Heads in 1000 trials: 0.501


## Question 7 (More Challenging)
Write a code to find the probability of both Heads and Tails for the same number of trials.

### Another Example - Card Game

We will now see a sample code where we will calculate conditional probability. The condition of calculating the probability is such that you first draw a face card (which is a given situation) and after you draw this first card what is the probability that your next card will be an ace?
Note: There are 4 Aces and 12 Face cards in a deck of 52 cards.

In [ ]:
 #Create function that returns probability percent rounded to one decimal place
def event_probability(event_outcomes, sample_space):
    probability = (event_outcomes / sample_space)
    return round(probability, 6)


# Sample Space
cards = 52

# Outcomes
aces = 4

# Divide possible outcomes by the sample set
ace_probability_percent = event_probability(aces,cards) *100

# Print probability percent rounded to one decimal place
print("probability % of finding aces, rounded to one decimal place: "+str(round(ace_probability_percent, 3)) + '%')


# Probability of drawing an ace, given you had just drawn a face card if you are the first player (the deck is NOT shuffled after the first draw)

face_cards = 12
face_card_probability = event_probability(face_cards, cards-1) # this is also the probability of the evidence

ace_probability= event_probability(aces,cards) #this is also the probability of the hypothesis

probability_face_card_n_ace=face_card_probability*ace_probability

conditional_probability= probability_face_card_n_ace / face_card_probability

print("probability % of drawing an ace, given a face card was just drawn: "+str(round(conditional_probability,5)*100)+'%')


probability % of finding aces, rounded to one decimal place: 7.692%
probability % of drawing an ace, given a face card was just drawn: 7.692%


## Question 8
From a given deck of 52 cards you first draw a king. What is the probability of finding another king from the same deck, considering the first card is already outside of the deck now? Write a code to calculate the conditional probability of getting the second card as another king.